### PR TITLE
Added and style mic button to enlarged shared screen view

### PR DESCRIPTION
**Pull request by stefkamarton**
Issue: #615

### CODE REVIEW

**Comment by so010** [comment]
I see as first step to clean up existing code because different versions of media controls exist right now in 
1. components/Countainers/Me.js two times (for smallContainer and !smallContainer which is true for "mobile" view and filmStrip view)
2. components/Controls/ButtonControlBar.js (if "Separate media controls" is activated)
And we don't need another incarnation of this in FullScreenView.js ;)

Would be nice to have only one component (ButtonControlBar.js) which we use everywhere we need media controls. The version in components/Countainers/Me.js is the most up to date one and should be copy pasted to components/Controls/ButtonControlBar.js and and then use component ButtonControlBar.js in Me.js instead.

After that we could include this component in components/VideoContainers/FullScreenView.js and display it the same way as we do if "Separate media controls" is activated.

**Comment by so010** [comment]
Good I like the button hide / unhide. But can you resolve merge conflicts?
Would be nice to have unhide onMouseMove as well.

**Comment by stefkamarton** [comment]
I added autohide feature to it.
I resolved merge conflicts but I can't compiled `FullScreenView.js` beacuse this branch doesn't contains `@react-hook/window-size` module.
After merge, It will work in `develop` branch.

**Comment by stefkamarton** [comment]
I added autohide feature to it and I resolved merge conflicts.

**Pull request merged**
