### PR TITLE
Add distinct audio notification with rate-limiting.

### PR DESCRIPTION
**Pull request by jmencak**
Introducing optionally configurable distinct audio notification with an optional delay between them.  This is configurable in `app/public/config/config.js` via the "notificationSounds" object.

Added two sample audio files.
  - `notify-chat.mp3`: from sound-theme-freedesktop (Debian) package;
    Copyright: Ivica Bukvic; License: CC-BY-SA-3.0
  - `notify-hand.mp3`: from
    https://samplefocus.com/collections/notification-sounds
    License: Public Domain

### CODE REVIEW

**Comment by jmencak** [comment]
@so010 please let me know if I'm on the right track.  Intending to use the `notifications` object in the future to set some rate-limiting of notifications.

**Comment by so010** [comment]
looks good!

**Comment by jmencak** [comment]
Changed the configuration key from "notifications" to "notificationSounds" to leave some room for configuring (rate-limiting) on-screen notifications.  Perhaps use `notificationOnScreen` in the future?

**Comment by so010** [comment]
:+1:

**Pull request merged**
