### PR TITLE
Disable simulcast if only 1 encoding profile defined

### PR DESCRIPTION
**Pull request by Astagor**
Continuation of changes from #717

### CODE REVIEW

**Comment by Astagor** [comment]
@so010 I have finished these changes, there are 2 points to discuss. Maybe a short call?

**Comment by Astagor** [comment]
After a long test session with @so010 we have decided to make a hack, as mediasoup has some kind of a bug for 320 resolution. It always sends the worst profile in simulcast, instead the best....

Should I merge? @so010

**Comment by vpalmisano** [comment]
This can be useful: https://chromium.googlesource.com/external/webrtc/+/master/media/engine/simulcast.cc#90

**Comment by so010** [comment]
I see no other good solution so we have to live with the bug for now. So, yes please merge but remove ( encodings && encodings.length > 1 ) as we discussed because it is meaningless together with the hack.

**Comment by Astagor** [comment]
I did that already. Merging.

**Pull request merged**
