### PR TITLE
Less aggressive ICE restarts.

### PR DESCRIPTION
**Pull request by jmencak**
Changes:
  - restart send/receive transport selectively; do not
    restart both of them on ICE disconnect/fail of only one of them.
  - wait for 2s on ICE disconnect/fail received from mediasoup-client
    before performing restartIce(); the restart is then cancelled if
    the ICE transport state changes within those 2s.
  - exponential backoff on ICE restart failures.

### CODE REVIEW

**Comment by jmencak** [comment]
This is still work-in-progress.  However, tested on Firefox 85, Chromium 88, Opera 74.  Still resolves https://github.com/edumeet/edumeet/issues/656 and there is also a significantly lower number of ICE restarts during bad network conditions as simulated within issue https://github.com/edumeet/edumeet/issues/656.

**Comment by jmencak** [comment]
/cc @Astagor 
Hope this helps with the issues you were seeing with https://github.com/edumeet/edumeet/pull/685

Still fixes https://github.com/edumeet/edumeet/issues/656

**Comment by Astagor** [comment]
Looks OK I guess, I personally do not like timeouts so, but if you have tested it, we can give it a try. I have tested just the simple flag on my users and now I only get very rarely a 401, and if then single, not many in a row. @so010 what do you think about this PR?

**Comment by jmencak** [comment]
> Looks OK I guess, I personally do not like timeouts so, but if you have tested it, we can give it a try. I have tested just the simple flag on my users and now I only get very rarely a 401, and if then single, not many in a row. @so010 what do you think about this PR?

I've tested that yesterday eve and this morning. I now get roughly 4x less ICE restarts in adverse network conditions while the video/audio stream is still resumed once the conditions improve.  The reason for the 4x less restarts is separating the send/receive for the restart and the fact that I "wait/timeout" for 2s as sometimes the restart is cancelled because of going from 'disconnected' -> 'connecting/connected'.  So that's the reason for the timeouts.

**Comment by Astagor** [comment]
@so010 did you have a look? I have tested it and it looks OK for me. Should I do a merge?

**Comment by Astagor** [comment]
On the other hand I had a look at my Coturn logs and I see
607014: : IPv4. tcp or tls connected to: 83.6.110.138:58058
607014: : session 001000000000008712: realm <webrtc.medvc.eu> user <>: incoming packet message processed, error 401: Unauthorized
607014: : IPv4. Local relay addr: 172.16.238.100:40515
607014: : session 001000000000008712: new, realm=<webrtc.medvc.eu>, username=<astagor>, lifetime=3600
607014: : session 001000000000008712: realm <webrtc.medvc.eu> user <astagor>: incoming packet ALLOCATE processed, success
607014: : session 001000000000008712: peer 168.119.227.11 lifetime updated: 300
607014: : session 001000000000008712: realm <webrtc.medvc.eu> user <astagor>: incoming packet CREATE_PERMISSION processed, success
607015: : session 000000000000008596: usage: realm=<webrtc.medvc.eu>, username=<astagor>, rp=2001, rb=2269972, sp=47, sb=7892
607015: : session 000000000000008596: peer usage: realm=<webrtc.medvc.eu>, username=<astagor>, rp=47, rb=4508, sp=2001, sb=2178793


There is first a call with no authentication data and then with authentication. So it seems that the ICE restarts are sending a lot of these request without auth data set. Why>

**Comment by jmencak** [comment]
> @so010 did you have a look? I have tested it and it looks OK for me. Should I do a merge?

I think the question is merge or revert https://github.com/edumeet/edumeet/pull/685 because this will produce considerably less ICE restarts.  If you don't want any, then revert, but https://github.com/edumeet/edumeet/issues/656 won't be fixed.

**Comment by Astagor** [comment]
I am not complaining that there are ICE restarts, I'm not sure why the request does not have auth data and causes 401s.

**Comment by jmencak** [comment]
> I am not complaining that there are ICE restarts, I'm not sure why the request does not have auth data and causes 401s.

Understood.  Also trying to figure out the right way forward as we have a sub-optimal ICE restart code in the develop branch at the moment.  Hence the revert/merge question.  I'll try to spend more time to try and reproduce the 401 coturn issues.  I suspect you don't have any data indicating which browser type might be causing this?  All or just a specific one?

**Comment by misi** [comment]
@Astagor  Can you please send me in private the logs, I want to check this 401 is more then interesting to be honest we need to have the full ice és pc state changes to understand the full picture, but may I understand more the issue. Thx

**Comment by jmencak** [comment]
So I managed to reproduce this.  However, I can reproduce this even when not using https://github.com/edumeet/edumeet/pull/685 , so what I (and perhaps you as well) am seeing is very likely not connected with the ICE restart PRs at all.

I believe we're seeing a correct response 401 from the turn server as described by [rfc8489](https://tools.ietf.org/html/rfc8489#section-9.1.3) as the username was not provided.  I can trigger this simply by using Firefox and entering a room as a participant.  Misi will probably have more to share on this, but those 401 seem to be part of the protocol to mean *so far* "Unautheticated" rather than "Unauthorized".  In fact, as mentioned in the RFC, IANA has changed the name of the 401 error code from "Unauthorized" to "Unauthenticated".

**Pull request merged**
