### PR TITLE
Restart ICE on disconnected/failed connection states.

### PR DESCRIPTION
**Pull request by jmencak**
Resolves issue https://github.com/edumeet/edumeet/issues/656.

Tested on firefox-85.0 and chromium-88.

### CODE REVIEW

**Comment by so010** [comment]
:)

**Comment by Astagor** [comment]
On my server I have started to see a lot of 
RTC::IceServer::ProcessStunPacket() | wrong authentication in STUN Binding Request => 401
logs. Is this related?

**Comment by jmencak** [comment]
I've been running this for a more than a week and I don't see these.  However, I don't have much users on the system and I also have other customizations such as the latest mediasoup/mediasoup-client.  I'll try to dig more into this.  Note that the ICE restarts should only occur during 'disconnect'/'failed' connectionstatechange.  Can you turn on the debug for ICE restarts and see if and how often you see these?  I'll try to do the same and do a bit more testing on a "normal" network, not simulating any packet loss/latency.

**Comment by Astagor** [comment]
It is difficult, this is a server, where when being used there are 200 users in like 8 rooms. So turning on debug generates hordes of logs. I have reverted the version before this pull request was merged and the 401 disappeared from the log. So I'm 99% sure this is causing it. But, the question is why do the logs appear? Probably 'disconnect'/'failed' has occurred, and restart on ICE was fired, but why then a 401? Something is not correctly configured? I'm using COTURN as my ICE server, maybe there is some problem? @misi

**Comment by jmencak** [comment]
You might be onto something with the coturn.  While I have eduMEET configured to use coturn, I've 1) reverted the FF patch for issue #72  and 2) all of my users (so far) are behind "friendly" FWs so that TURN is not used at all.  I've tested this yesterday (without TURN) for cca 2 hours of video calls, occasionaly simulating network latency, packet loss, bw throttling.  No issues you describe found in the logs.  Only the benefit of video/audio unfreezing after I removed the bw throttling as soon as ICE restart happened.

**Pull request merged**
