### PR TITLE
Feat advanced audio options

### PR DESCRIPTION
**Pull request by vpalmisano**
Restructured audio settings interface adding all advanced controls to store.

Checklist:
- [x] store migrations changing with `window.config.version` value
- [x] preset settings in app config
- [x] define more presets and check if the values are actually applied

output

### CODE REVIEW

**Comment by roman-drozd-it** [comment]
Looks very good!

**Comment by so010** [comment]
I like it - especially separate audio / video tabs.
Do you want to make ptime parameter available as well?

**Comment by vpalmisano** [comment]
Added with the latest commit.
I0ve changed the suggested ptime values (https://groups.google.com/g/discuss-webrtc/c/G4hXCBq7Qgo)

**Comment by so010** [comment]
> Added with the latest commit.
> I've changed the suggested ptime values:
> 
> https://groups.google.com/g/discuss-webrtc/c/G4hXCBq7Qgo
> https://chromium.googlesource.com/external/webrtc/+/HEAD/api/audio_codecs/opus/audio_encoder_opus_config.cc#56

Interesting, we should test/discuss this. Especially how we can control SILK / CELT mode and pTime.
I feel there is something essential to get here.

**Comment by vpalmisano** [comment]
With the latest commit I've added the audio analyser.
A list of display options can be found here: https://audiomotion.dev/demo/overlay.html

https://user-images.githubusercontent.com/283319/115278276-8fa98900-a145-11eb-9367-cb082692248b.mp4

**Comment by vpalmisano** [comment]
Latest version with rewritten visualization interface:

https://user-images.githubusercontent.com/283319/115409194-d359cc80-a1f1-11eb-8309-99b19affb221.mp4

**Comment by vpalmisano** [comment]
Last version screencast:

https://user-images.githubusercontent.com/283319/115581867-afb58580-a2c8-11eb-9e8c-5b8d63607f8e.mp4

**Comment by Alex-YddeR** [comment]
Please check this i have deployed on server to test this feat, found dropdown values are not visible in this section.

Screenshot 2021-04-23 at 9 35 23 AM

**Comment by so010** [comment]
Y

> Please check this i have deployed on server to test this feat, found dropdown values are not visible in this section.

Did you updated your config file according to new config - example?

**Comment by Alex-YddeR** [comment]
Yes i just copied config.example.js to config.js.

Thanks

**Pull request merged**
