### PR TITLE
Error: worker._routers is not iterable

### PR DESCRIPTION
**Pull request by mikasmart**
View https://github.com/edumeet/edumeet/issues/930

worker._routers is not iterable

### CODE REVIEW

**Comment by danisharora099** [comment]
Does this code run without errors?

Because I think this misses the logic to handle pipeToRouter code which also uses private variables from the Mediasoup Worker class

**Comment by mikasmart** [comment]
No mistake detected (only for me).
I don't understand why this problem appeared. Maybe an evolution of the Mediasoup Worker.

**Comment by danisharora099** [comment]
Yeah Mediasoup updated their package to deprecate use of private variables publicly

**Comment by Astagor** [comment]
This is not complete. I will fix this soon.

**Pull request closed without merging**
