### PR TITLE
Updated documentation and Debian packet build github action

### PR DESCRIPTION
**Pull request by sd4v1d**

### CODE REVIEW

**Review by roman-drozd-it — CHANGES_REQUESTED** [review]
- [x] default port is changed to `443`, 
- [x] the same a peace of config
- [ ] it seems you didn't generate/update `app/README.md` by` gen-config-docs  ` or maybe I missed something

I would delete a bolded: "**To change default options,** create your own server config file (yaml or json)", beacuse "use template" also change the default values

**Comment by sd4v1d** [comment]
Thanks for review. You are correct regarding bolded part,  and when you pointed that, I would say that whole configuration part are somehow misleading. True is that it will use default options if there is no configuration files. However, for server part, configuration options are split between two different config files: config.js (from config.example.js) for authentication and participant role logic, and config.{yaml, json} for all other options. I will change my PR and propose different text for configuration part. 
Regarding app/README.md, no I didn't change/update that since that file is auto-generated. Should I (and what exactly)?

**Comment by roman-drozd-it** [comment]
> Regarding app/README.md, no I didn't change/update that since that file is auto-generated. Should I (and what exactly)?

I got you PR and after: `app$ yarn gen-config-docs` `server$ yarn gen-config-docs`, there are some changes to commit and push, frankly didn't check how much related with your changes, but generate them and push to PR.

**Comment by sd4v1d** [comment]
Imho, app/README.md and server/README.md are not related with this PR since there is no direct connection with main README.md file except that there is link pointing to those two files. However, there are some parameters in those two files which are specific to local server/computer  (like IP address or CPU cores), and those values are dynamically set during document generation. That is the reason why there is change in those two files on every run of the gen-config-docs.

**Comment by roman-drozd-it** [comment]
> Imho, app/README.md and server/README.md are not related with this PR since there is no direct connection with main README.md file except that there is link pointing to those two files. 

Not exacly, I see you have modified the `config.ts` so should always update/generate the config doc `app/README.md` and `config.example.js` when you do so.

**Comment by sd4v1d** [comment]
I did some more work in reorganising configuration documentation, please see how it looks at my fork [sd4v1d:release-3.5.0](https://github.com/sd4v1d/edumeet/tree/release-3.5.0).
In short:
- introduced yarn and json example templates
- edited configuration section in main README
- removed duplicated information from ./app and ./server README files and which now contains only generated parameters list
- added escape sequence for two dynamically set values on every server `gen-config-docs` run
- checked that production port is set to 443 in all configuration files (I hope that I din't missed some :-) )

**Pull request merged**
