### PR TITLE
fixed Issue with devices on IOS when connected with Airpods

### PR DESCRIPTION
**Pull request by abdulrabbt**
fixed when devicechange is fired multiple time without any devices shanges

### CODE REVIEW

**Comment by vpalmisano** [comment]
Why have you re-formatted the roomClient.js source code? It is very difficult to review you changes.

**Comment by Alex-YddeR** [comment]
This issue with all apple IOS mobile devices whether they connect with wired headphones or bluetooth ear phones.

**Comment by roman-drozd-it** [comment]
@abdulrabbt Can you provide your PR with keeping the default formatting?

**Comment by Alex-YddeR** [comment]
This is fixed with latest iOS update.

**Comment by so010** [comment]
not relevant any longer

**Pull request closed without merging**
