### PR TITLE
Safari Screen Share Bug Fix

### PR DESCRIPTION
**Pull request by abhisheksingh07**
Screen Share option is not activate in latest safari version.
Fix changes made in 'src/app/deviceInfo.js'.
On any version of safari, screen share option is available. User able to share the screen.

### CODE REVIEW

**Comment by Astagor** [comment]
This not a fix, you are setting always 14.0 for all safari browsers. In ScreenShare.js there is

				case 'safari':
				{
					if (device.version >= 13.0)
						return new DisplayMediaScreenShare();
					else
						return new DefaultScreenShare();
				}
So starting from Safari 13.0 screen sharing should work. The only cause if it does not work, is that the version parser does not return a correct number and the if condition fails. I do not have a Safari 14 to test but, you could provide an output what version gets detected (print out device.version in ScreenShare.js), of course without you changes.

**Comment by abhisheksingh07** [comment]
I am using the safari version 14.1.1 
Screenshot 2021-08-06 at 1 24 51 PM
Screenshot 2021-08-06 at 1 23 46 PM;

I got the correct version of safari without my changes.

**Comment by Astagor** [comment]
Yes, this is a bug, but your code is not a fix, as 
if ('14.0' >= '4.0')
is false. you cannot compare strings with >=
We will provide a fix.

**Comment by abhisheksingh07** [comment]
Thank you so much.

**Comment by Astagor** [comment]
Have a look at #894 this fixes the problem in develop branch. If you are using master, you can just copy the 2 lines that I have changed.

**Pull request closed without merging**
