### PR TITLE
Adding Typescript Support

### PR DESCRIPTION
**Pull request by alangecker**
during the rework of RoomClient #740, I proposed to move towards typescript. In a call with some of the edumeet dev's people were happy about that and it seemed like consent among the present people.

I thought it makes sense to have that in a separate PR - here it is!

### included changes
- **typescript support**
- **eslint rules for typescript** \
   I decided for the [airbnb style](https://www.npmjs.com/package/eslint-config-airbnb-typescript), since it seems like more or less a standard now and it also matches my personal code style quite well :)
- **yarn as the package manager** \
  `npm install` on the current `develop` didn't work at all. after a while of unsuccessful debugging, I tried out `yarn` and it worked immediately without any problems. Additionally is yarn way more performant.

### CODE REVIEW

**Comment by misi** [comment]
Thanks! Cool..

**Comment by vpalmisano** [comment]
Tested right now inside the docker compose environment, it works without problems, after deleting the app/node_modules directory and re-launching the edumeet container.

**Comment by alangecker** [comment]
I've added now typescript and yarn with the same linting settings to the backend as well.

**Comment by so010** [comment]
:+1:

**Comment by misi** [comment]
We need to update docker... :-/ Docker autobuild fail

**Comment by vpalmisano** [comment]
I've pushed some modifications required for running the ts version on server side.

**Pull request merged**
