### PR TITLE
Local recording feature

### PR DESCRIPTION
**Pull request by N7Remus**
Local recording for Tabs/Applications/Screens. 
The video+audio streams are stored in local indexedDB and after the recording is stopped it is downloaded with StreamSaver.js as a File Stream.

This feature is disabled for Safari.
Works on firefox - Mozilla Firefox 87.0 - but no sound from the shared window/tab/screen only from the Mic of the person who is recording.
Works with Opera - Version : 75.0.3969.171
works with Chrome : Version: 90.0.4430.72 (Offical build) (64 bit) (On linux you can only record application audio for Tabs)
Works with Edge - Version: 91.0.852.0 (Offical build) dev (64 bit)
Tested on Ubuntu 20.04.2

### CODE REVIEW

**Comment by alangecker** [comment]
first thanks for the work! I think having a data privacy friendly option to record conferences without storing the data on the server will be great advantage over other video conferencing solutions! :)

Currently I try to keep an overview for upcoming changes with could conflict with the removal/refactor of RoomClient.js (#740).
In this PR you add quite a lot of code to the already big and chaotic file I try to remove :D

For me it seems like the recording itself is (apart from the `sendRequest()` and usage of `_micProducer`) completely independent of the backend and the other WebRTC/Streaming code and more like a general browser recording feature?

I wonder whether this could not go into a different place like:

### Idea: Local Recording in the Store
- in Topbar.js: `dispatch(recordingActions.startRecording(roomClient));`
- async redux-thunk actions `recordingActions.js`:
  ```js
  const recorder = new BrowserRecorder()
  
  export const startLocalRecording = (roomClient) => {
	return async (dispatch, getState) => {
		const state = getState()
		const micProducer = Object.values(state.producers).find(p => p.source === 'mic')

		const additionalAudioTracks = []
		if(micProducer) additionalAudioTracks.push(micProducer.track)

		try {
			await recorder.start({
				additionalAudioTracks,
				recordingMimeType,
				constraints: RECORDING_CONSTRAINTS
			})
			await roomClient.sendRequest('setLocalRecording', { localRecordingState: RECORDING_START });
			dispatch(setLocalRecordingState(RECORDING_START));
		} catch(err) {
			// ...
		}
	}
  }
  ```
- and separated a `BrowserRecorder.js` which is abstracted in a way that it could potentially also be used everywhere without any connection to edumeet (open source ♥!)
  ```js
  export default class BrowserRecorder {
	async start({additionalAudioTracks, recordingMimeType, constraints}) {
		// ...
	}
	stop() {
		// ...
	}
	invokeSaveAsDialog() {
		// ...
	}
  }
  ```
  
feel free to approach me at any time if you have any questions! :) (@chandi at slack)

**Comment by Alex-YddeR** [comment]
Do we need to disable echo cancellation for recording.? Far-end users audio get records only when disabling echo cancellation but disabling that making lots of disturbance in the session.

Thanks

**Comment by ThumbstackTech** [comment]
#72

**Comment by hkizilhan** [comment]
For audio recording:
is it possible to merge other participants audio streams with audiocontext and feed merged stream to mediarecorder?

**Comment by N7Remus** [comment]
> For audio recording:
> is it possible to merge other participants audio streams with audiocontext and feed merged stream to mediarecorder?

Yes it is possible, i'm working on it.

**Comment by hkizilhan** [comment]
> > For audio recording:
> > is it possible to merge other participants audio streams with audiocontext and feed merged stream to mediarecorder?
> 
> Yes it is possible, i'm working on it.

I'm glad to hear that. Do you have an estimate for completion?

**Comment by N7Remus** [comment]
> > > For audio recording:
> > > is it possible to merge other participants audio streams with audiocontext and feed merged stream to mediarecorder?
> > 
> > 
> > Yes it is possible, i'm working on it.
> 
> I'm glad to hear that. Do you have an estimate for completion?

I think it's stable and done. I will test it a bit more and  merge it on monday.

**Pull request merged**
