### PR TITLE
lib-edumeet: Major refactoring of RoomClient.js

### PR DESCRIPTION
**Pull request by alangecker**
hey lovely edumeet folk!

### Background
After benchmarking different Videoconferencing solutions, I was quite happy with the results of Edumeet. Especially the client-side performance with even >200 Clients was promising!

Since [we](https://github.com/zirkuszelt) wanted to integrate edumeet as a matrix/element widget, I was looking deeper into the frontend. Maybe it can be modified easily? If not, maybe there is even something like [lib-jitsi-meet](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api) which would make it really easy to writing an own minimal frontend without bothering to much about the webrtc/media stuff?

Than I had my first look into the `RoomClient.js` and, to be honest, I was quite shocked...^^ 4.5k Lines, webrtc stuff, store management, key listeners, torrent creation, event handling, etc... everything dumped in a single file. Looks like since the fork of the `mediasoup-demo`, it was just append-only without reflecting on the a good structure and separation of concerns.

but because I somehow felt in love with mediasoup, I decided to spent some effort in refactoring this mess :>

### Approach
Analogous to `lib-jitsi-meet`, split off all Backend communication and WebRTC/Media Handling from the frontend UI into a own library `lib-edumeet` and offer a clear API for reusing it for potential new frontend projects for edumeet.

Also the code is split into different components

##### Components
- `lib-edumeet`
  - `SignalingAPI`: Communication with the edumeet server
  - `Transport`: Mediasoup transport handling
  - `Producers`: everything which produces Media (mic,webcam,screenshare,extraVideo)
  - `Consumers`: everything which consumes Media of other peers
  - `Files`: File exchange (torrent)
  - `Room`: Wraps together the components, room state
- [`RoomAdapter`](https://github.com/alangecker/edumeet/blob/lib-edumeet/app/src/RoomAdapter.ts): calls to lib-edumeet, listen to events and update redux store

Since I'm also in love with Typescript, because it provides type safety and great intellisense support, I went to that path with `lib-edumeet` :) 

### Wish
Feedback! I spent already to much time in the code, so that I feel quite limited in my thinking-out-of-the-box-capacity. Maybe the whole approach is wrong? Maybe the separation could be changed? Or just some variable names are misleading?

At the end there should be an easy to use API for creating new frontends, If there is any thought which might make it easier, please tell me! :)

### ToDo's
1. [x] Main work of refactoring into new structure
2. [x] Move into own package `/lib-edumeet`
3. [x] Merge typescript support #758
4. [x] Awaiting merge of #777  and #781
4. [x] Rebase on top of current `develop`
5. [x] refactor `enableOpusDetails` 
7. [ ] review & testing

### CODE REVIEW

**Comment by so010** [comment]
Hi @alangecker! 
Yes,  `RoomClient.js` is a mess and needs complete rewrite - this is highly appreciated! 
To make a lib-edumeet is the most obvious step :+1: 

We want to come in contact with you - could we discuss this more directly? Do you would like to participate in one of our developer meetings? Is tomorrow from 13.30 (1.30pm) possible?

**Comment by alangecker** [comment]
@so010 unfortunately tomorrow won't work for me, but I'm happy to get in contact! :)
Matrix: @chandi:livingutopia.org
Mail: me at chandi.it

**Comment by so010** [comment]
I've sent you an email.

**Comment by havfo** [comment]
The structure seems sane to me, haven't had time to go through everything in detail. I see there is still a lot of cleanup to do, but a very good start :+1:

I ran lint and it output the following on the branch as it currently stands:
`✖ 1534 problems (889 errors, 645 warnings)`

The lint config also need an update for Typescript.

**Comment by alangecker** [comment]
@havfo 

> I ran lint and it output the following on the branch as it currently stands:
> `✖ 1534 problems (889 errors, 645 warnings)`
> 
> The lint config also need an update for Typescript.

this will be solved after the #758 PR including the linting/formatting settings got merged :)

**Comment by stemcc** [comment]
Now that #777 and #781 have both been merged into the develop branch, this refactor just needs to rebase on the current develop branch before being merged. Are there any other blockers besides keeping this from getting merged besides the rebase now?

**Comment by alangecker** [comment]
@stemcc
I don't see any more blockers either ;) Will try to find some time for the rebase in the next 2 weeks!

**Comment by alangecker** [comment]
rebase is now done :tada:

- for the sake of easiness I disabled `enableOpusDetails` for now. Moving that to lib-edumeet requires some more work, but I wanted to get a running state of lib-edumeet first.
- I noticed, that passing `accessCode` in the constructor is currently not implemented yet.
- Eventually there are bugs in the file sharing. could not test that yet.
- **well-assured there are bugs on lot of places. I would be happy if people could already test this branch! :)**

**Comment by roman-drozd-it** [comment]
Some problem with missed dependencies (in package.json):

**host spec:**
```
debian   10.10
arch     x86_64
bash     5.0.3
------
chrome   91.0.4472.101
node     16.1.0 | 14.15.4
 ↪ n     7.0.1
 ↪ npm   7.11.2
 ↪ yarn  1.21.1
git      2.20.1
```

**What I've done:**
```
gh pr checkout 740 # (fetch PR)
git worktree add ../lib-edumeet lib-edumeet  # (create workspace for it)
cd ../lib-edumeet/
cp app/public/config/config.example.js app/public/config/config.j
cp server/config/config.example.js server/config/config.js
cd app
```
```
yarn && yarn build
```


> yarn run v1.21.1
> $ react-app-rewired build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/
> /home/romek/log/emt/src/lib-edumeet/app/src
> Creating an optimized production build...
> Failed to compile.
> 
> /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/Consumers.ts
> TypeScript error in /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/Consumers.ts(3,18):
> Could not find a declaration file for module 'hark'. '/home/romek/log/emt/src/lib-edumeet/app/node_modules/hark/hark.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/hark` if it exists or add a new declaration (.d.ts) file containing `declare module 'hark';`  TS7016
> 
>     1 | import * as mediasoupClient from 'mediasoup-client';
>     2 | import Bowser from 'bowser';
>     3 | import hark from 'hark';
>       |                  ^
>     4 | import { stringArrayEqual } from './utils';
>     5 | import { EventEmitterTyped, IEventsDescriptor } from './EventEmitter';
>     6 | import EdumeetTransport from './Transport';
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
> 
> 

```
yarn add --dev @types/hark # (as suggested in the above error log)
yarn build
```

> 
> yarn run v1.21.1
> $ react-app-rewired build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/
> /home/romek/log/emt/src/lib-edumeet/app/src
> Creating an optimized production build...
> Failed to compile.
> 
> /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/Files.ts
> TypeScript error in /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/Files.ts(91,4):
> Could not find a declaration file for module 'create-torrent'. '/home/romek/log/emt/src/lib-edumeet/app/node_modules/create-torrent/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/create-torrent` if it exists or add a new declaration (.d.ts) file containing `declare module 'create-torrent';`  TS7016
> 
>     89 | 			/* webpackPrefetch: true */
>     90 | 			/* webpackChunkName: "createtorrent" */
>     91 | 			'create-torrent'
>          | 			^
>     92 | 		);
>     93 | 		
>     94 | 		const torrent: Torrent = await new Promise( (resolve, reject) => {
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> 

```
yarn add --dev @types/create-torrent # (as suggested in the above error log)
yarn build
```


> yarn run v1.21.1
> $ react-app-rewired build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/
> /home/romek/log/emt/src/lib-edumeet/app/src
> Creating an optimized production build...
> Failed to compile.
> 
> /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/SignalingAPI.ts
> TypeScript error in /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/SignalingAPI.ts(1,28):
> Could not find a declaration file for module 'socket.io-client'. '/home/romek/log/emt/src/lib-edumeet/app/node_modules/socket.io-client/lib/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/socket.io-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'socket.io-client';`  TS7016
> 
>     1 | import SocketIOClient from 'socket.io-client';
>       |                            ^
>     2 | import Logger from './Logger';
>     3 | import { EventEmitterTyped, IEventsDescriptor } from './EventEmitter';
>     4 | import { SocketTimeoutError, timeoutCallback, getSignalingUrl } from './utils';
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 

```
yarn add --dev @types/socket.io-client # (as suggested in the above error log)
yarn build
```

> yarn run v1.21.1
> $ react-app-rewired build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/
> /home/romek/log/emt/src/lib-edumeet/app/src
> Creating an optimized production build...
> Failed to compile.
> 
> /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/SignalingAPI.ts
> TypeScript error in /home/romek/log/emt/src/lib-edumeet/app/node_modules/lib-edumeet/src/SignalingAPI.ts(90,23):
> Cannot find namespace 'SocketIOClient'.  TS2503
> 
>     88 | 
>     89 | export default class SigalingAPI extends EventEmitterTyped<APIEvents> {
>    90 |     private _socket?: SocketIOClient.Socket
>        |                       ^
>     91 |     get socket(): SocketIOClient.Socket {
>     92 |     	if (!this._socket) throw new Error('signaling socket is used, but not defined. call Room.join() first');
>     93 |
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 

Stuck here.

**Comment by alangecker** [comment]
apparently a normal `yarn` execution doesn't install the `devDependencies` of lib-edumeet.
what I used for development is
```bash
cd lib-edumeet
yarn link
cd ../app
yarn link lib-edumeet
```
this symlinks the lib into `node_modules` and apparently also installs its devDependencies.

I'll check tomorrow how this issue can be resolved! ;)

**Comment by sd4v1d** [comment]
Hi, 
It seems that it is enough to copy devDependencies and Dependencies entries from  lib-edumeet/package.json to app/package.json.

**Comment by alangecker** [comment]
the method with `yarn link` or `npm link` (like mentioned my post above) seems to be the standard for connecting local modules and effectively using the module including its devDependencies. 

I updated now the `README` and `Dockerfile` to apply this.

```bash
cd lib-edumeet
yarn link
yarn
cd ../app
yarn link lib-edumeet
yarn
```

**Comment by piranna** [comment]
What's the status of this?

**Comment by roman-drozd-it** [comment]
@piranna waiting for its turn. we will take care of it after the new release, which will take place in the next few days. I can't give you even an approximate date when we'll handle it.

**Comment by so010** [comment]
@alangecker are you still out there? We have now full focus on refactoring client code and began from scratch with a little bit more radical approach:
https://github.com/edumeet/edumeet-client
We took many of your ideas and appreciate your contributions. Please join us there!

**Pull request closed without merging**
